# Generated by Django 4.1.7 on 2023-03-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('badge_no', models.CharField(max_length=10, unique=True)),
                ('code_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('secret_mission', models.TextField()),
                ('active', models.BooleanField()),
                ('no_of_assignments', models.IntegerField()),
            ],
        ),
    ]
